<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "html5mediaelements"
 *
 * Auto generated by Extension Builder 2015-10-28
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'HTML5 Media Elements',
	'description' => '',
	'category' => 'plugin',
	'author' => 'Simon Praetorius',
	'author_email' => 'praetorius@wiro-consultants.de',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '2.1.1',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);