<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "html5mediaelements"
 *
 * Auto generated by Extension Builder 2015-10-28
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'HTML5 Media Elements',
	'description' => 'A media plugin that embeds audio and video files using HTML5 tags and Adobe Flash as a fallback. If the command line utilities "ffmpeg" and "ffprobe" are available on the server, a scheduler task can be configured to convert the source files to web-friendly media formats such as mp4, webm and mp3. The goal is to make embedding local media files as easy as uploading a video to YouTube.',
	'category' => 'plugin',
	'author' => 'Simon Praetorius',
	'author_email' => 'praetorius@wiro-consultants.de',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => false,
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '2.2.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2.0-7.6.0',
		),
		'conflicts' => array(
		),
		'suggests' => array(
			'scheduler' => ''
		),
	),
);